// Keep projects separate so your HTML stays tidy.
// Access via global: window.PROJECTS
window.PROJECTS = [
  { id:'frc4063', title:'Team 4063 FRC Robot', badges:['robotics','embedded'], summary:'Competition robot design & programming for FRC 4063.', img:'./assets/project-1.png.JPG', links:{code:'https://github.com/ricMejia1', live:'https://youtu.be/uuoONiXpf4c?si=wNI9PEBVdEZ8wm8m'}, details:`<p><strong>Focus:</strong> drivetrain, controls, wiring, driver practice.</p><ul><li>Sensor integration & autonomous routines.</li><li>Match strategy and pit operations.</li></ul>` },
  { id:'linetracker', title:'Line Tracking Robot', badges:['robotics','embedded'], summary:'Sensor-guided line follower with control tuning.', img:'./assets/project-2.png.JPG', links:{code:'https://github.com/ricMejia1/LineTrackingRobot', live:'https://github.com/ricMejia1'}, details:`<p><strong>Stack:</strong> Logic based programming, Quartus Prime.</p><ul><li>Reliable line detection and cornering.</li></ul>` },
  { id:'expandlet', title:'Expandlet (CAD)', badges:['cad'], summary:'Expandable outlet that retracts in wall to keep everything organized.', img:'./assets/project-3.png.jpg', links:{code:'https://github.com/ricMejia1/expandlet', live:'https://cad.onshape.com/documents/25098a4e49e090ec0328f6b9/w/deb332f122e549273e05fcb3/e/46866bcea86862d21a10f647?renderMode=0&uiState=6680e86c6f7b3b4c17906bec'}, details:`<p><strong>Tools:</strong> Onshape CAD. Parametric parts and hinges.</p>` },
  { id:'smartglow', title:'SmartGlow IoT Light System', badges:['iot','embedded'], summary:'Door/motion sensors drive a servo light switch with web UI.', img:'./assets/project-4.png', links:{code:'https://github.com/ricMejia1/SmartGlow-w-IoT.git', live:'https://drive.google.com/drive/folders/1qkIUoG9tqhSB6-Iv2N89J7lXyul8X8fk?usp=drive_link'}, details:`<p><strong>Stack:</strong> STM32 HAL, Raspberry Pi gateway, Flask/JS dashboard.</p><ul><li>OTA config and metrics logging.</li></ul>` },
  { id:'capacitorcar', title:'Capacitor-Powered Car Model', badges:['embedded'], summary:'Energy storage demo car; analysis & testing.', img:'./assets/project-5.png', links:{code:'https://drive.google.com/drive/folders/19SNVW9SbtQgfNyMUM3OWf6Z7b2OE8k4k?usp=drive_link', live:'https://youtu.be/_35I5piISPE?si=t393JVbpvvCSy-3K'}, details:`<p><strong>Focus:</strong> discharge profiles & gearing.</p>` },
  { id:'k2639', title:'K2639 Liquid Controller Analysis', badges:['embedded'], summary:'Reverse-engineering & control behavior study.', img:'./assets/project-6.png', links:{code:'https://drive.google.com/drive/folders/1Jzd1oSr262niJ4GPv5OLErfCrSrziRyg?usp=drive_link', live:'#'}, details:`<p>Captured response curves and threshold behavior.</p>` },
];
